language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install django --use-mirrors
  - pip install python-magic --use-mirrors
  - pip install -e . --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run --source=validatedfile runtests.py
notifications:
  email:
    recipients:
      - jespinog@gmail.com
      - andres.moya@kaleidos.net
    on_success: change
    on_failure: change
after_success:
  - coveralls
